services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root  # Changez ce mot de passe
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql        # Persistance des données
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db                    # Nom du service MySQL dans le réseau Docker
      PMA_PORT: 3306
    ports:
      - "81:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:


